require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, min_ios_version_supported
prepare_react_native_project!

target 'app' do
  config = use_native_modules!

  use_react_native!(
    :path => config[:reactNativePath],
    :hermes_enabled => false
  )

  # Permissions
  pod 'RNPermissions', :path => '../node_modules/react-native-permissions'

  # Explicitly require only the permissions you need
  pod 'Permission-Contacts', :path => '../node_modules/react-native-permissions/ios/Contacts'

  target 'appTests' do
    inherit! :complete
    # Pods for testing
  end

  post_install do |installer|
    react_native_post_install(installer)
  end
end